export const imagePrompts = [
  'Photograph of a high-energy football match, players mid-action, stadium lights illuminating the field, fans cheering passionately, 4k resolution.',
  'Digital art of a contemporary art gallery, visitors admiring abstract paintings, with a minimalist and modern design, Blender, Cycles render.',
  'Detailed sketch of a gourmet dish, seared scallops on a bed of puree, garnished with microgreens, capturing the essence of fine dining, crisp details.',
  'Photograph of a playful golden retriever chasing a frisbee in a sunlit park, capturing the joy and energy of the moment, 8k resolution.',
  'Photograph of a state-of-the-art laboratory, scientists working on groundbreaking experiments, futuristic equipment glowing, 4k clarity.',
  'Photograph of a bustling basketball court in New York, players showing off their skills, spectators watching intently, 4k resolution.',
  'Photograph of visitors marveling at the Mona Lisa in the Louvre, capturing the awe and wonder of the iconic masterpiece, 4k clarity.',
  'Detailed drawing of a sushi platter, showcasing the vibrant colors of fresh sashimi, wasabi, and pickled ginger, crisp details.',
  'Photograph of a majestic tiger lounging in the grass, its eyes locked onto the camera, capturing its raw power and beauty, 8k resolution.',
  'Photograph of a modern rooftop garden, city skyline in the backdrop, people enjoying the green oasis amidst urban chaos, 4k clarity.',
  'Gnome village during autumn, surrounded by colorful trees, highly detailed, Blender, Cycles render, 4k resolution.',
  'Dynamic photography portrait of a robot, golden ornate armor, elegant, Photograph, octane 4k render.',
  "Photograph of a tennis match during sunset, players' silhouettes against the orange sky, ball mid-air, capturing the intensity of the game, 4k clarity.",
  'Photograph of a bustling café in Madrid, patrons enjoying tapas, with the historic streets of the city visible through the window, 4k resolution.',
  'Detailed sketch of a DNA helix, capturing the intricacies of the genetic code, symbolizing the wonders of science, crisp details.',
  "Photograph of a vibrant farmer's market, stalls overflowing with fresh produce, people sampling and buying, capturing the essence of local culture, 4k clarity.",
  'Photograph of a serene aquarium, colorful fish swimming amidst corals, children pressing their faces against the glass in wonder, 8k resolution.',
  'Photograph of a lively salsa dance event, dancers in colorful attire, moving in sync, capturing the rhythm and passion of the dance, 4k clarity.',
  'Digital art of a contemporary sculpture exhibit, abstract metal and stone pieces, visitors contemplating the meaning, set in a minimalist gallery space, Blender render.',
  'Detailed drawing of a steaming bowl of ramen, soft-boiled egg, and sliced pork, capturing the comfort of the dish, crisp details.',
  'Photograph of a curious cat peeking out from behind a curtain, its eyes wide and playful, capturing a candid moment, 8k resolution.',
  'Photograph of a night at the observatory, astronomers gazing at the stars, telescopes pointing at the vast cosmos, 4k clarity.',
  'Photograph of a vibrant street mural in progress, artist spray-painting a wall, passersby stopping to admire, capturing urban art culture, 4k resolution.',
  'Digital art of a bustling food festival, stalls offering cuisines from around the world, people tasting and enjoying, set against a city park backdrop, Blender, Cycles render.',
  'Photograph of a hummingbird in flight, wings a blur, sipping nectar from a flower, capturing the marvel of nature, 8k clarity.',
  'Photograph of a viking ship sailing under the aurora borealis, with snow-capped mountains in the distance, 4k resolution.',
  'Charcoal sketch of a roaring 1920s jazz club, musicians, flapper dancers, and an energetic crowd, crisp details.',
  'Digital art of a hidden mountain monastery, monks in meditation, waterfalls, and cherry blossoms, inspired by Tibetan landscapes, Blender, Cycles render.',
  'Detailed drawing of a wristwatch, showcasing the intricate mechanics, leather strap, inspired by luxury watch advertisements, crisp details.',
  'Scientist exploring an alien jungle on Venus, hyper-realistic, intricate details, 4k render.',
  'Artistic rendition of a lighthouse during a storm, inspired by the works of Thomas Kinkade, 4k resolution.',
  'Phoenix rising from ashes, acrylic painting, vibrant colors, detailed feathers, inspired by the works of Stanley Lau, 4k clarity.',
  'Whales flying in the evening sky, surreal digital art, Eevee render, dreamlike and detailed, 4k resolution.',
  'Portrait of a knight with silver armor reflecting the moonlight, digital art, 4k render.',
  'Photograph of a dancer in motion, capturing the fluidity and grace, 4k, crisp details, inspired by dance photography.',
  'Photograph of a marathon, runners pushing their limits, spectators cheering, capturing the essence of endurance and determination, realistic, 4k render.',
  'Acrylic painting of a bustling train station, old steam engine, passengers waiting, evoking the romance of early 20th-century travel, 4k clarity.',
  'Oil painting of a mountain hiking trail, backpackers ascending, panoramic view of valleys below, embodying adventure and exploration, 4k resolution.',
  'Sorceress casting a spell under a full moon, gothic, detailed attire, graphite sketch, intricate patterns, inspired by the works of H.R. Giger, 4k clarity.',
  '70mm detailed photograph of a chameleon on a vibrant flower, Canon EOS 5D, outdoors, vibrant colors, depth of field, sharp, 4k resolution.',
  'Aerial shot of the Eiffel Tower during twilight, natural hues, professional shot, 4k, crisp details.',
  'Photograph of a butterfly with gears and cogs, steampunk theme, vibrant, 6k, high clarity.',
  'Photograph of a jazz band performing on stage, saxophonist in focus, dimly lit ambiance, capturing the soul of the music, 4k clarity.',
  'Detailed sketch of a vintage car, chrome reflections, leather seats, capturing the essence of the 1960s automotive design, crisp details.',
  'Photograph of a serene lake with reflections of the northern lights, calm waters, 4k resolution.',
  'Watercolor of a rainy day in Paris, people with umbrellas, wet cobblestone streets reflecting the city lights, 4k clarity.',
  'Digital art of a bustling market street, vendors, colorful stalls, and a crowd of diverse people shopping, Blender, Cycles render, 4k resolution.',
  'Artistic representation of a lion with golden mane and emerald eyes, under studio lights, trending on Pinterest, highly detailed, 4k clarity.',
  'Photograph of a street musician, playing a saxophone, passersby stopping to listen, capturing the magic of impromptu performances, 4k resolution.',
  'Digital art of a cityscape floating on clouds, neon lights, cyberpunk theme, vibrant colors, trending on Artstation, Blender, Cycles render, 4k resolution.',
  'Realistic photo of a majestic white stag in a snowy forest, morning light filtering through trees, 50mm, serene, 4k clarity.',
  'Digital art of a serene bamboo forest with floating lanterns, oriental theme, calm, Blender, Cycles render, 4k resolution.',
  'Photograph of morning dew on a rose, macro shot, Canon EOS R5, vibrant colors, sharp details, 8k clarity.',
  'Digital art of a cozy winter evening, family around a fireplace, hot cocoa in hand, capturing warmth and comfort, Blender, Cycles render, 4k resolution.',
  'Mountain village during winter, digital art, snowy rooftops, warm lights from windows, inspired by the works of Simon Stålenhag, 4k clarity.',
  'Charcoal sketch of a musician playing the violin under a streetlamp, vintage theme, detailed shadows and highlights, crisp details.',
  'Digital rendition of a family having a picnic on a floating island, bright and sunny, isometric 3D, inspired by Studio Ghibli scenes, Blender, Cycles render, 4k resolution.',
  'Digital art of a futuristic city skyline at dusk, neon signs, flying cars, and towering skyscrapers, Blender, Cycles render, 4k clarity.',
  'Oil painting of a serene countryside, golden fields of wheat, a lone tree, and distant mountains under a pastel sky, 4k resolution.',
  'Photograph of a surfer riding a massive wave, capturing the raw power of the ocean, high-speed shot, 4k clarity.',
  'Graphite sketch of an astronaut floating in space, reflecting the Earth in the visor, detailed spacesuit, 4k resolution.',
  'Digital art of an enchanted forest, glowing mushrooms, fairy creatures, and a magical pond reflecting the moon, Blender, Cycles render, 4k clarity.',
  'Watercolor painting of a bustling Tokyo street at night, pedestrians with umbrellas, neon lights, and rain-soaked streets, 4k clarity.',
  'Photograph of a majestic eagle in flight, mountains in the background, capturing the essence of freedom, 4k clarity.',
  'Photograph of a desert landscape, sand dunes casting long shadows, a lone camel silhouette against the setting sun, 8k resolution.',
  'Digital art of a steampunk-inspired train, puffing steam, traveling on a track suspended in the air, intricate metalwork, Blender, Cycles render, 4k clarity.',
  'Charcoal sketch of a ballerina in a graceful pose, capturing the elegance and fluidity of the dance, crisp details.',
  'Photograph of an ancient temple ruins, overgrown with moss and vines, misty ambiance, evoking a sense of mystery, 4k clarity.',
  'Photograph of a post-apocalyptic city, remnants of skyscrapers, nature reclaiming the land, inspired by the works of Jakub Rozalski, 4k resolution.',
  'Watercolor of a Venetian canal at sunset, gondolas, historic buildings, and reflections in the water, 4k clarity.',
  'Digital art of a robot and a child holding hands, walking through a meadow, juxtaposing technology and nature, Blender, Cycles render, 4k resolution.',
  'Photograph of a dense forest, sunlight filtering through the canopy, creating a mosaic of light and shadow on the forest floor, 8k clarity.',
  'Photograph of a viking ship sailing under the aurora borealis, with snow-capped mountains in the distance, 4k clarity.',
  'Charcoal sketch of a roaring 1920s jazz club, musicians, flapper dancers, and an energetic crowd, crisp details.',
  'Digital art of a hidden mountain monastery, monks in meditation, waterfalls, and cherry blossoms, inspired by Tibetan landscapes, Blender, Cycles render, 4k clarity.',
];
