export const imagePrompts = [
  'Gnome village during autumn, surrounded by colorful trees, highly detailed, Blender, Cycles render.',
  'Detailed drawing of a wristwatch, showcasing the intricate mechanics, leather strap, inspired by luxury watch advertisements.',
  'Scientist exploring an alien jungle on Venus, hyper-realistic, intricate details, 4k render.',
  'Artistic rendition of a lighthouse during a storm, inspired by the works of Thomas Kinkade.',
  'Phoenix rising from ashes, acrylic painting, vibrant colors, detailed feathers, inspired by the works of Stanley Lau.',
  'Whales flying in the evening sky, surreal digital art, Eevee render, dreamlike and detailed.',
  'Portrait of a knight with silver armor reflecting the moonlight, digital art, 4k render.',
  'Photograph of a dancer in motion, capturing the fluidity and grace, 4k, crisp details, inspired by dance photography.',
  'Photograph of a marathon, runners pushing their limits, spectators cheering, capturing the essence of endurance and determination, realistic, 4k render.',
  'Acrylic painting of a bustling train station, old steam engine, passengers waiting, evoking the romance of early 20th-century travel.',
  'Oil painting of a mountain hiking trail, backpackers ascending, panoramic view of valleys below, embodying adventure and exploration.',
  'Sorceress casting a spell under a full moon, gothic, detailed attire, graphite sketch, intricate patterns, inspired by the works of H.R. Giger.',
  '70mm detailed photograph of a chameleon on a vibrant flower, Canon EOS 5D, outdoors, vibrant colors, depth of field, sharp.',
  'Aerial shot of the Eiffel Tower during twilight, natural hues, professional shot, 4k, crisp details.',
  'Photograph of a butterfly with gears and cogs, steampunk theme, vibrant, 6k, high clarity.',
  'Photograph of a jazz band performing on stage, saxophonist in focus, dimly lit ambiance, capturing the soul of the music.',
  'Detailed sketch of a vintage car, chrome reflections, leather seats, capturing the essence of the 1960s automotive design.',
  'Digital painting of a serene lake with reflections of the northern lights, calm waters.',
  'Watercolor of a rainy day in Paris, people with umbrellas, wet cobblestone streets reflecting the city lights.',
  'Digital art of a bustling market street, vendors, colorful stalls, and a crowd of diverse people shopping.',
  'Artistic representation of a lion with golden mane and emerald eyes, under studio lights, trending on Pinterest, highly detailed.',
  'Photograph of a street musician, playing a saxophone, passersby stopping to listen, capturing the magic of impromptu performances.',
  'Digital art of a cityscape floating on clouds, neon lights, cyberpunk theme, vibrant colors, trending on Artstation.',
  'Realistic photo of a majestic white stag in a snowy forest, morning light filtering through trees, 50mm, serene.',
  'Digital art of a serene bamboo forest with floating lanterns, oriental theme, calm.',
  'Photograph of morning dew on a rose, macro shot, Canon EOS R5, vibrant colors, sharp details.',
  'Digital art of a cozy winter evening, family around a fireplace, hot cocoa in hand, capturing warmth and comfort.',
  'Mountain village during winter, digital art, snowy rooftops, warm lights from windows, inspired by the works of Simon Stålenhag.',
  'Charcoal sketch of a musician playing the violin under a streetlamp, vintage theme, detailed shadows and highlights.',
  'Digital rendition of a family having a picnic on a floating island, bright and sunny, isometric 3D, inspired by Studio Ghibli scenes.',
  'Digital art of a futuristic city skyline at dusk, neon signs, flying cars, and towering skyscrapers.',
  'Oil painting of a serene countryside, golden fields of wheat, a lone tree, and distant mountains under a pastel sky.',
  'Photograph of a surfer riding a massive wave, capturing the raw power of the ocean, high-speed shot, 4k.',
  'Graphite sketch of an astronaut floating in space, reflecting the Earth in the visor, detailed spacesuit.',
  'Digital art of an enchanted forest, glowing mushrooms, fairy creatures, and a magical pond reflecting the moon.',
  'Watercolor painting of a bustling Tokyo street at night, pedestrians with umbrellas, neon lights, and rain-soaked streets.',
  'Photograph of a majestic eagle in flight, mountains in the background, capturing the essence of freedom, 4k clarity.',
  'Digital painting of an underwater city, merfolk, colorful corals, and marine creatures, bioluminescent glow.',
  'Oil painting of a medieval castle on a hill, surrounded by a moat, with a drawbridge and torch-lit battlements.',
  'Photograph of a desert landscape, sand dunes casting long shadows, a lone camel silhouette against the setting sun.',
  'Digital art of a steampunk-inspired train, puffing steam, traveling on a track suspended in the air, intricate metalwork.',
  'Charcoal sketch of a ballerina in a graceful pose, capturing the elegance and fluidity of the dance.',
  'Photograph of an ancient temple ruins, overgrown with moss and vines, misty ambiance, evoking a sense of mystery.',
  'Digital painting of a post-apocalyptic city, remnants of skyscrapers, nature reclaiming the land, inspired by the works of Jakub Rozalski.',
  'Watercolor of a Venetian canal at sunset, gondolas, historic buildings, and reflections in the water.',
  'Digital art of a robot and a child holding hands, walking through a meadow, juxtaposing technology and nature.',
  'Photograph of a dense forest, sunlight filtering through the canopy, creating a mosaic of light and shadow on the forest floor.',
  'Digital painting of a viking ship sailing under the aurora borealis, with snow-capped mountains in the distance.',
  'Charcoal sketch of a roaring 1920s jazz club, musicians, flapper dancers, and an energetic crowd.',
  'Digital art of a hidden mountain monastery, monks in meditation, waterfalls, and cherry blossoms, inspired by Tibetan landscapes.',
];
